name: Release Go binary
on:
  release:
    types: [created]
permissions:
  contents: write
  packages: write
jobs:
  release-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-w -s"
          executable_compression: upx
          md5sum: FALSE
          sha256sum: TRUE
