name: Publish to AUR
on:
  push:
    branches:
      - master
    paths:
      - PKGBUILD
jobs:
  aur-publish:
    if: github.repository_owner == 'tfkhdyt'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        with:
          pkgname: exchango-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
